### ISSUE TITLE
想请问下你们的CWS是如何测试的？

### ISSUE THREAD

**Issue by kFoodie** [fastnlp/fastHan#1]
首先感谢大佬们分享。
我想请问你下你们的CWS是怎么测试得到的F值？
看到test.py里面有写了一些数据，但是不知道这些测试数据具体是怎样的形式。不知道方便分享一下测试的代码或者数据吗？

**Comment by fdugzc** [comment]
目前上面的test.py、train.py就是测试和训练的代码，但是大家不能直接运行，因为这几个文件是我对未封装的模型训练调参用的，与当前环境下文件的目录结构无法匹配，发上来是为了给对训练过程感兴趣的朋友参考一下。
test.py中的数据，chars_vocab\label_vocab是fastNLP中的Vocabulary类（标签集、词表）。all_data是一个词典，共有train\test\dev三个key，对应了三个词典，此处三个词典又分别具有14个key（代表4项任务的13个语料库），对应了14个fastNLP的DataSet类，其中包含了输入序列、序列长度、序列的标签等信息。对于CWS的数据，每个DataSet由若干条下方元组组成：
+--------------------------+--------------------------+---------+
| words                              | target                            | seq_len  |
+--------------------------+--------------------------+---------+
| ['[unused2]', '许','可', '...  | ['S', 'B', 'E', 'B', ...              | 24         |
+--------------------------+--------------------------+---------+
具体的测试算法，使用了fastNLP中的tester与SpanFPreRecMetric。fastNLP提供了从训练模型到测试模型的一系列流程代码。

**Comment by fdugzc** [comment]
订正一下，CWS的数据当中，输入序列不是字符序列，而是已经被Vocabulary处理过的数字序列；此外每个元组中还包括当前数据的任务类别，即CWS。
