### ISSUE TITLE
调用模型报错

### ISSUE THREAD

**Issue by lllllliutongtong** [fastnlp/fastHan#10]
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://212.129.155.247/fasthan/fasthan_base.zip (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
zsh: terminated  env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1   --default --client --host

**Comment by fdugzc** [comment]
现在下载模型的服务器出了点问题，在修复中

**Comment by fdugzc** [comment]
已经好了，刚才是服务器的流量超了

**Comment by lllllliutongtong** [comment]
> 现在下载模型的服务器出了点问题，在修复中



> 已经好了，刚才是服务器的流量超了
好滴！

**Comment by zxjlm** [comment]
这个错误又出现了，请问可以把模型发一份到邮箱吗？或者用网盘中转一下？  zxjlm233@163.com 🧐

**Comment by fdugzc** [comment]
@zxjlm 你看看现在能下了吗？上午服务器出了点问题

**Comment by zxjlm** [comment]
> @zxjlm 你看看现在能下了吗？上午服务器出了点问题

嗯，可以了，多谢😆

**Comment by lllllliutongtong** [comment]
邮件我已收到~
