### ISSUE TITLE
分词 粒度问题

### ISSUE THREAD

**Issue by lizhangtao** [fastnlp/fastHan#13]
支持 basic 和 fhrase粒度吗？
CWS：AS, CITYU, CNC, CTB, MSR, PKU, SXU, UDC, WTB, ZX
是通过设置这个来决定切词粒度吗？有更具体的说明吗

**Comment by fdugzc** [comment]
并不支持basic和fhrase粒度；可以参考readme的“分词风格”一节，关于语料库的覆盖面和分词粒度等更详细的信息可以在语料库的项目网站中查询
