### ISSUE TITLE
下载后的模型，后期想使用模型路径调用模型

### ISSUE THREAD

**Issue by yecphaha** [fastnlp/fastHan#18]
fastHan初次下载模型后，无法使用模型路径调用模型。函数里只有一个“model_type”的参数，很不方便。

**Comment by fdugzc** [comment]
正常来讲，在model_type里选定模型后，就会自动加载模型路径中的模型了。您执行的时候代码没有找到对应模型吗？可以发一下报错信息吗？

**Comment by yecphaha** [comment]
@fdugzc 
## 自定义代码
    def _get_model(self, model_type):

        # 首先检查本地目录中是否已缓存模型，若没有缓存则下载。

        if model_type == 'base':
            url = 'http://212.129.155.247/fasthan/fasthan_base.zip'
            model_dir = cached_path(url, name='fasthan')
            return model_dir
        elif model_type == 'large':
            url = 'http://212.129.155.247/fasthan/fasthan_large.zip'
            model_dir = cached_path(url, name='fasthan')
            return model_dir
        elif len(model_type) > 5:
            return model_type
        else:
            raise ValueError("model_type can only be base or large.")
            model_dir = cached_path(url, name='fasthan')
            return model_dir

**Comment by yecphaha** [comment]
@fdugzc 我的意思是如果我把模型放到另一个文件内，FastHan就无法调用模型了，因为model_type参数只能是base或者large，无法通过模型路径进行调用。

**Comment by YeChaopeng** [comment]
@fdugzc ，上面的自定义代码是我基于修改源代码，来满足我的需求。model_type可以传入模型当前所在的路径。
from fastHan import FastHan
model=FastHan(model_type='D:/code/ai_platform/NER/fastNLP_ner/fasthan_large')
# model=FastHan(model_type='large')

sentence="郭靖是金庸笔下的一名男主。"
answer=model(sentence,target="NER")
print(answer)

**Comment by yecphaha** [comment]
@fdugzc ，上面的自定义代码是我基于修改源代码，来满足我的需求。model_type可以传入模型当前所在的路径。

from fastHan import FastHan
model=FastHan(model_type='D:/code/ai_platform/NER/fastNLP_ner/fasthan_large')
sentence="郭靖是金庸笔下的一名男主。"
answer=model(sentence,target="NER")
print(answer)

**Comment by fdugzc** [comment]
按照您自定义的代码，可以把模型所在的目录作为model_type参数传入，如果目录里所需要的文件齐全，就可以加载了。

**Comment by fdugzc** [comment]
嗯嗯，看来您已经自行解决了问题。

**Comment by yecphaha** [comment]
是啊，我的意思是现在模型会被下载到用户目录的路径下，但是如果模型被剪切到另一个路径下，FastHan就无法加载模型了。是否可以在下一版本里增加这个小需求呢？

**Comment by fdugzc** [comment]
可以的，到时候会和其他功能一起在下一个版本更新：）

**Comment by yecphaha** [comment]
@fdugzc 谢谢啦
