### ISSUE TITLE
Which directory to place the downloaded file?

### ISSUE THREAD

**Issue by limkonghua** [fastnlp/fastHan#19]
Which directory to place the "fasthan_base.zip" 

/opt/anaconda3/lib/python3.7/site-packages/fastNLP/io
(base) [limkh@tarcbda io]$ ls -lrt
total 72
-rw-rw-r--. 1 limkh limkh  2365 Dec 14 12:03 __init__.py
-rw-rw-r--. 1 limkh limkh 20393 Dec 14 12:03 file_utils.py
-rw-rw-r--. 1 limkh limkh  5376 Dec 14 12:03 file_reader.py
-rw-rw-r--. 1 limkh limkh  8656 Dec 14 12:03 embed_loader.py
-rw-rw-r--. 1 limkh limkh 18920 Dec 14 12:03 data_bundle.py
-rw-rw-r--. 1 limkh limkh  3543 Dec 14 12:03 utils.py
-rw-rw-r--. 1 limkh limkh  1499 Dec 14 12:03 model_io.py
drwxrwxr-x. 3 limkh limkh   223 Dec 14 12:03 loader
drwxrwxr-x. 3 limkh limkh   208 Dec 14 12:03 pipe
drwxrwxr-x. 2 limkh limkh   232 Dec 14 12:03 __pycache__
(base) [limkh@tarcbda io]$

I think firewall in the network block it,  whereas I can download base through another network. The following is the error:

  File "/opt/anaconda3/lib/python3.7/site-packages/fastNLP/io/file_utils.py", line 459, in get_from_cache
    raise HTTPError(f"Status code:{req.status_code}. Fail to download from {url}.")
requests.exceptions.HTTPError: Status code:403. Fail to download from http://212.129.155.247/fasthan/fasthan_base.zip.

**Comment by fdugzc** [comment]
`
import os
os.path.expanduser(os.path.join("~", ".fastNLP","fasthan"))
`
Run this code and you can get a path. 
Put the .zip file at this directory ,unzip it, delete the .zip file then you can use it.

**Comment by fdugzc** [comment]
`
import os

os.path.expanduser(os.path.join("~", ".fastNLP","fasthan"))
`
Run this code and you can get a path.
Put the .zip file at this directory ,unzip it, delete the .zip file then you can use it.
