### ISSUE TITLE
有去停用词功能吗？

### ISSUE THREAD

**Issue by lurocdong** [fastnlp/fastHan#2]
而且文档中能否对不同的分词style做个说明。

**Comment by fdugzc** [comment]
因为模型在训练时，不对输入字符串做任何清洗等处理，目前暂时没有去停用词功能。分词style，指的是训练模型中文分词模块的10个语料库，模型可以区分这10个语料库，设置分词style为S即令模型认为现在正在处理S语料库的分词。所以分词style实际上是与语料库的覆盖面、分词粒度相关的。目前已知的是，ctb的分词粒度较细，as与cityu语料库为繁体语料库。文档中将会添加各个语料库的来源。

**Comment by lurocdong** [comment]
好的，谢谢！
