### ISSUE TITLE
期待新版本能处理超过512的长句！

### ISSUE THREAD

**Issue by trzhang-ai** [fastnlp/fastHan#22]
在做长句的分词时，我通常会先根据中文标点符号分句，再对句子碎片进行分词。然而，在部分场景下，用中文标点分出来的句子仍然很长。其原因当然与语料作者没有按照正常中文书面语使用习惯有关，处理的方法当然可以用长度硬拆，但是这样会在数据预处理阶段引入误差。如果作者能解决长句的分词问题就太好啦！

**Comment by fdugzc** [comment]
该功能正在开发中：）
