### ISSUE TITLE
url模型路径调用错误

### ISSUE THREAD

**Issue by yecphaha** [fastnlp/fastHan#24]
from fastHan import FastHan
model = FastHan(url="D:/code/term weight/Q2/fasthan_large")
sentence = "诺基亚（NOKIA）105 新 黑色 直板按键 移动2G手机 老人老年手机 学生备用功能机 超长待机 双卡双待"
answer = model(sentence)
print(answer)

报错：
Traceback (most recent call last):
  File "D:/code/term weight/Q2/segment.py", line 40, in <module>
    model = FastHan(url="D:/code/term weight/Q2/fasthan_large")
  File "E:\python\lib\site-packages\fastHan\FastModel.py", line 121, in __init__
    self.model.load_state_dict(model_state_dict)
  File "E:\python\lib\site-packages\torch\nn\modules\module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CharModel:
	Unexpected key(s) in state_dict: "embed.model.encoder.encoder.layer.4.attention.self.query.weight", "embed.model.encoder.encoder.layer.4.attention.self.query.bias", "embed.model.encoder.encoder.layer.4.attention.self.key.weight", "embed.model.encoder.encoder.layer.4.attention.self.key.bias", "embed.model.encoder.encoder.layer.4.attention.self.value.weight", "embed.model.encoder.encoder.layer.4.attention.self.value.bias", "embed.model.encoder.encoder.layer.4.attention.output.dense.weight", "embed.model.encoder.encoder.layer.4.attention.output.dense.bias", "embed.model.encoder.encoder.layer.4.attention.output.LayerNorm.weight", "embed.model.encoder.encoder.layer.4.attention.output.LayerNorm.bias", "embed.model.encoder.encoder.layer.4.intermediate.dense.weight", "embed.model.encoder.encoder.layer.4.intermediate.dense.bias", "embed.model.encoder.encoder.layer.4.output.dense.weight", "embed.model.encoder.encoder.layer.4.output.dense.bias", "embed.model.encoder.encoder.layer.4.output.LayerNorm.weight", "embed.model.encoder.encoder.layer.4.output.LayerNorm.bias", "embed.model.encoder.encoder.layer.5.attention.self.query.weight", "embed.model.encoder.encoder.layer.5.attention.self.query.bias", "embed.model.encoder.encoder.layer.5.attention.self.key.weight", "embed.model.encoder.encoder.layer.5.attention.self.key.bias", "embed.model.encoder.encoder.layer.5.attention.self.value.weight", "embed.model.encoder.encoder.layer.5.attention.self.value.bias", "embed.model.encoder.encoder.layer.5.attention.output.dense.weight", "embed.model.encoder.encoder.layer.5.attention.output.dense.bias", "embed.model.encoder.encoder.layer.5.attention.output.LayerNorm.weight", "embed.model.encoder.encoder.layer.5.attention.output.LayerNorm.bias", "embed.model.encoder.encoder.layer.5.intermediate.dense.weight", "embed.model.encoder.encoder.layer.5.intermediate.dense.bias", "embed.model.encoder.encoder.layer.5.output.dense.weight", "embed.model.encoder.encoder.layer.5.output.dense.bias", "embed.model.encoder.encoder.layer.5.output.LayerNorm.weight", "embed.model.encoder.encoder.layer.5.output.LayerNorm.bias", "embed.model.encoder.encoder.layer.6.attention.self.query.weight", "embed.model.encoder.encoder.layer.6.attention.self.query.bias", "embed.model.encoder.encoder.layer.6.attention.self.key.weight", "embed.model.encoder.encoder.layer.6.attention.self.key.bias", "embed.model.encoder.encoder.layer.6.attention.self.value.weight", "embed.model.encoder.encoder.layer.6.attention.self.value.bias", "embed.model.encoder.encoder.layer.6.attention.output.dense.weight", "embed.model.encoder.encoder.layer.6.attention.output.dense.bias", "embed.model.encoder.encoder.layer.6.attention.output.LayerNorm.weight", "embed.model.encoder.encoder.layer.6.attention.output.LayerNorm.bias", "embed.model.encoder.encoder.layer.6.intermediate.dense.weight", "embed.model.encoder.encoder.layer.6.intermediate.dense.bias", "embed.model.encoder.encoder.layer.6.output.dense.weight", "embed.model.encoder.encoder.layer.6.output.dense.bias", "embed.model.encoder.encoder.layer.6.output.LayerNorm.weight", "embed.model.encoder.encoder.layer.6.output.LayerNorm.bias", "embed.model.encoder.encoder.layer.7.attention.self.query.weight", "embed.model.encoder.encoder.layer.7.attention.self.query.bias", "embed.model.encoder.encoder.layer.7.attention.self.key.weight", "embed.model.encoder.encoder.layer.7.attention.self.key.bias", "embed.model.encoder.encoder.layer.7.attention.self.value.weight", "embed.model.encoder.encoder.layer.7.attention.self.value.bias", "embed.model.encoder.encoder.layer.7.attention.output.dense.weight", "embed.model.encoder.encoder.layer.7.attention.output.dense.bias", "embed.model.encoder.encoder.layer.7.attention.output.LayerNorm.weight", "embed.model.encoder.encoder.layer.7.attention.output.LayerNorm.bias", "embed.model.encoder.encoder.layer.7.intermediate.dense.weight", "embed.model.encoder.encoder.layer.7.intermediate.dense.bias", "embed.model.encoder.encoder.layer.7.output.dense.weight", "embed.model.encoder.encoder.layer.7.output.dense.bias", "embed.model.encoder.encoder.layer.7.output.LayerNorm.weight", "embed.model.encoder.encoder.layer.7.output.LayerNorm.bias".

**Comment by yecphaha** [comment]
为什么会报错，因为model_type默认是base，但是模型路径是large。所以正确写法是model = FastHan(model_type="large", url="D:/code/term weight/Q2/fasthan_large")

**Comment by yecphaha** [comment]
源码里
def __init__(self,model_type='base',url=None):

---------------------------------------------------

#创建新模型
        if model_type=='base':
            layer_num=4
        else:
            layer_num=8

所以使用教程里的模型路径的使用方法需要改一下，改为
model=FastHan(model_type="base", url="C:/Users/gzc/.fastNLP/fasthan/fasthan_base")
## model_type是必填项

**Comment by yecphaha** [comment]
还有一个问题是用户词典添加4个字的词，模型无法分出来。

from fastHan import FastHan
model = FastHan(model_type="large", url="D:/code/term weight/Q2/fasthan_large")
sentence = "诺基亚（NOKIA）105 新 黑色 直板按键 移动2G手机 老人老年手机 学生备用功能机 超长待机 双卡双待"
answer = model(sentence)
print(answer)
model.add_user_dict(["功能机", "双卡双待"])
answer = model(sentence, use_dict=True)
print(answer)

输出：
[['诺基亚', '（', 'NOKIA', '）', '105 ', '新', ' ', '黑色', ' ', '直板', '按键', ' ', '移动2G', '手机', ' ', '老人', '老年', '手机', ' ', '学生', '备用', '功能', '机', ' ', '超长', '待机', ' ', '双', '卡', '双', '待']]
[['诺基亚', '（', 'NOKIA', '）', '105 ', '新', ' ', '黑色', ' ', '直板', '按键', ' ', '移动2G', '手机', ' ', '老人', '老年', '手机', ' ', '学生', '备用', '功能机', ' ', '超长', '待机', ' ', '双', '卡', '双', '待']]

**Comment by fdugzc** [comment]
感谢你发现的关于model_type的bug以及解决方案。
对于用户词典问题，如果词典中都是像["功能机", "双卡双待"]这种高召回率的词，可以用model.set_user_dict_weight函数增大一下词典的权重系数。比如这里model.set_user_dict_weight(1)就够了。如果权重系数设置的足够高，相当于对词典中的词100%召回。条件允许的话可以自己构造dev set来找一个最优的系数。
