### ISSUE TITLE
模型在哪里下载

### ISSUE THREAD

**Issue by Pean-Mura** [fastnlp/fastHan#25]
预训练模型在哪里可以下载

**Comment by fdugzc** [comment]
正常情况下是自动下载的。如果是服务器无法连接外网，可以通过以下url手动下载：
base模型：http://212.129.155.247/fasthan/fasthan_base.zip
large模型：http://212.129.155.247/fasthan/fasthan_large.zip

**Comment by xrzlizheng** [comment]
无法下载

**Comment by fdugzc** [comment]
> 无法下载

刚刚服务器挂了。现在能下载吗？

**Comment by KyleWang-Hunter** [comment]
下载不了

**Comment by fdugzc** [comment]
> 下载不了

目前我们这里的服务器是没有问题的，您新开一个浏览器窗口，在地址中输入模型链接看能下载吗？

**Comment by KyleWang-Hunter** [comment]
> > 下载不了
> 
> 目前我们这里的服务器是没有问题的，您新开一个浏览器窗口，在地址中输入模型链接看能下载吗？

不行
