### ISSUE TITLE
为啥我的代码在服务器上运行特别慢，服务器是16核的，正常运行没有问题

### ISSUE THREAD

**Issue by Yanshichao0419Git** [fastnlp/fastHan#26]
![image](https://user-images.githubusercontent.com/87471971/125761658-5116775a-5cf0-4239-a5c5-82ecee7fe596.png)
这个运行出来大概需要3.5秒一个词，本地计算机跑就很快，大概一秒10条。服务器是centos7系统，本地是win10系统。

**Comment by Yanshichao0419Git** [comment]
本地跑一秒大概十多条，在服务器上跑大概3.5秒一条，代码未变化

**Comment by fdugzc** [comment]
服务器的其他用户有没有在使用cpu或者内存资源？内存如果占满了不停swap也会很卡。

排除其他问题后如果想继续提速的话，可以用set_device函数用gpu加速，以及batch化输入来提速

**Comment by Yanshichao0419Git** [comment]
使用top查看了cpu和内存资源全是fastHan在占用，现在使用的服务器没有GPU，现在正在与公司同事一起寻找原因，现在猜测是环境的问题，准备在docker内做一套干净的环境来测试。

**Comment by Yanshichao0419Git** [comment]
效率慢的原因是因为公司服务器内的CPU性能不行，现在使用GPU在跑，但是有的词性标注不太明白是什么词性，比如说EM，AS

**Comment by fdugzc** [comment]
定义和文档在官网上： https://www.cs.brandeis.edu/~clp/ctb/ 
我在一篇博客上也看到了一些解释：https://blog.csdn.net/lihaitao000/article/details/51812618

**Comment by Yanshichao0419Git** [comment]
好的感谢
