### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by cxfzzj** [fastnlp/fastHan#27]
求问：频繁调用，所占内存越来越大，最后程序被kill，这是为什么？？

**Comment by KyleWang-Hunter** [comment]
我也遇到了这个问题，请问你解决了吗？

**Comment by fdugzc** [comment]
能够确认是“越来越大”吗？是否为某一batch的数据长度/batch size较大，导致OOM？
比如导致报错的那一个batch，放到第一个运行，也会被kill吗？

**Comment by cxfzzj** [comment]
> 我也遇到了这个问题，请问你解决了吗？

似乎，一次处理的句子不能太多；batch_size给大了，就会内存一直涨。给个小的batch_size，比如8，是不会累计内存的

**Comment by cxfzzj** [comment]
> 能够确认是“越来越大”吗？是否为某一batch的数据长度/batch size较大，导致OOM？
> 比如导致报错的那一个batch，放到第一个运行，也会被kill吗？

不知道到是什么导致的内存增大，只是观测到在CPU上运行时，内存不断累积
