### ISSUE TITLE
请问fastHan能否支持aarch64环境下的使用？

### ISSUE THREAD

**Issue by caseylai** [fastnlp/fastHan#30]
如题，查看了一下fastHan的一些依赖包，如torch，看上去是没有在aarch64环境下编译过的，请问下是不能支持aarch64环境下的使用吗？

**Comment by fdugzc** [comment]
目前还没有尝试过在aarch64环境中使用

**Comment by caseylai** [comment]
> 目前还没有尝试过在aarch64环境中使用

我目前在aarch64环境（华为麒麟V10系统）上进行了一些尝试，目前已经调试通过，在此留下一些踩坑记录供后来者节省时间：

建议首先安装Anaconda的环境，Anaconda已经内置了很多的基础依赖包，可以为后续节省大量时间。另外，FastNLP有很多的依赖包，大多数依赖包在anaconda网站（anaconda.org/anaconda/repo）可以找到aarch64（或者noarch）的版本下载，在anaconda环境下安装，安装编译过程中的问题均已解决（主要是依赖包的版本兼容问题，有一些依赖库的安装可以通过系统包管理器安装或者rpm包安装），安装spacy时需要仔细解决各种依赖，非常考验耐心。torch的安装稍微不同，经测试anaconda的版本和kmtea的版本均有一些问题（虽然能安装使用，不会报错，但执行NER任务会没有结果返回，经仔细排查是torch计算全连接层时会在张量中引入莫名其妙的nan值，导致后续迭代中张量值全为nan），更换为 pypi.org 下载的torch版本后问题解决（链接地址：[https://pypi.org/project/torch/#files](https://pypi.org/project/torch/#files)，文件名：torch-1.10.0-cp39-cp39-manylinux2014_aarch64.whl）

另外，补充一下，fastHan真的很赞，非常感谢开发团队将这么好的作品开源！
