### ISSUE TITLE
保存的模型的chars_vocab和label_vocab乱码问题

### ISSUE THREAD

**Issue by hl0737** [fastnlp/fastHan#31]
尊敬的作者:
    您好, 请教下模型保存后的路径下的chars_vocab文件和label_vocab文件打开都是乱码, 请问如何解决?

    Windows10, 用记事本打开, 编码是ANSI

![image](https://user-images.githubusercontent.com/13363151/144989627-18dd924f-4d54-4188-bb7c-647a2e3732cc.png)
![image](https://user-images.githubusercontent.com/13363151/144989651-0c55a226-2b5b-4c1e-8cf7-e53ebae45622.png)

**Comment by fdugzc** [comment]
这两个文件是二进制文件，分别存储了一个Vocabulary类实例与dict类实例，需要使用 torch.load 函数来读取才能看到内容

**Comment by hl0737** [comment]
好的, 非常感谢作者快速的回复, 我爱你!
