### ISSUE TITLE
finetune Parsing任务不会自动finetune cws和pos任务

### ISSUE THREAD

**Issue by hl0737** [fastnlp/fastHan#33]
尊敬的作者:

    您好。我发现一个很有提升价值的点。

    如果我直接做parsing的finetune, 然后在测试集上看效果, 发现分词的效果很不好, 照理来说不应该这样, 所以我猜测Parsing任务没有包含cws和pos的finetune, 但是照理来说parsing的标签是包含了cws和pos的信息的.

    我先执行cws的finetune再执行parsing的finetune发现test集合上的分词效果很好.

    所以我理解在执行更高级的任务的时候, 可以先从最低级的任务开始finetune, 而且是自动完成这个过程.

   即如果finetune Parsing, 则先finetune cws, 然后finetune pos, 最后finetune parsing

   如果finetune pos, 则先finetune cws, 再finetune pos

   作者您怎么看?

**Comment by fdugzc** [comment]
这个问题确实存在，当时设计finetune的时候忽略了这一点。我做完当前的投稿之后会改一下这一条

**Comment by hl0737** [comment]
> 这个问题确实存在，当时设计finetune的时候忽略了这一点。我做完当前的投稿之后会改一下这一条

预祝 Best Paper
