### ISSUE TITLE
Chinese Dependency Parsing的SOTA模型

### ISSUE THREAD

**Issue by hl0737** [fastnlp/fastHan#36]
作者您好:

    我看了一下chinese dependency parsing在paperswithcode上的SOTA模型

    显示是这一篇Glyce: Glyph-vectors for Chinese Character Representations

    它的dependency parsing的分数89 L , 90.2 U, 而本项目readme中的文档中写的dependency parsing的SOTA的准确率没有这个高, 请问readme中是参考的哪篇的数据?

**Comment by fdugzc** [comment]
我们和Glyce用的数据集不一样，我们参考的是这篇：
A graph-based model for joint chinese word segmentation and dependency parsing

**Comment by hl0737** [comment]
> A graph-based model for joint chinese word segmentation and dependency parsing

作者你好, 我看了这一篇论文, 但是有点不解.

CTB 更新的数据集应该是包含旧的数据集的, 比如CTB9包含过去所有CTB的数据集, 这篇文章用了CTB 5 7 9来训练, 但是照理来说9的数据集是包含5和7的, 那为什么还要用5和7呢?
