### ISSUE TITLE
模型下载报错

### ISSUE THREAD

**Issue by Blemishine** [fastnlp/fastHan#46]
ConnectionError: HTTPConnectionPool(host='download.fastnlp.top', port=80): Max retries exceeded with url: /fasthan/fasthan.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4f2aecfd0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

是下载服务器又挂了吗？请问有没有其他的下载2.0版本的模型的方式呢？

**Comment by 1hhhhh** [comment]
请问你解决了吗

**Comment by hqu-little-boy** [comment]
> 请问你解决了吗


请问你解决了吗

**Comment by fdugzc** [comment]
请看 #49 #38
