### ISSUE TITLE
模型下载报错，请问可以提供百度网盘下载链接吗？

### ISSUE THREAD

**Issue by luckycucu** [fastnlp/fastHan#47]
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='download.fastnlp.top', port=80): Max retries exceeded with url: /fasthan/fasthan.zip (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000173052887C0>, 'Connection to download.fastnlp.top timed out. (connect timeout=None)'))

模型下载出错，请问可以提供百度网盘下载链接吗？

**Comment by fdugzc** [comment]
请看 #49 #38
