### ISSUE TITLE
请问之前有人下载成功fastHan2.0的模型吗，可以通过百度网盘或其他在线方式分享一下吗？保佑 拜托 拜托了

### ISSUE THREAD

**Issue by luckycucu** [fastnlp/fastHan#48]
![093810E1](https://github.com/fastnlp/fastHan/assets/40897539/ae2dab84-ade1-4da4-a870-9efc310b5af8)

**Comment by wuruiwen2000** [comment]
您好，请问解决了吗？我现在也无法通过服务器下载

**Comment by luckycucu** [comment]
没有，在知乎问了也没有回复。官方可能放弃了。

**Comment by zioworz** [comment]
您好，请问后面如何解决的，我现在也无法进行下载。

**Comment by fdugzc** [comment]
请看 #49 #38
