### ISSUE TITLE
请问词性英文缩写代表什么意义？

### ISSUE THREAD

**Issue by HarborZeng** [fastnlp/fastHan#6]
您好，非常感谢您开发的这个fastHan，不过在使用过程中，想问问这些词性标注都代表了什么意思呢？

```
[[['WuLi', 6, 'nsubj', 'NR'], ['，', 4, 'punct', 'PU'], ['网络', 4, 'nn', 'NN'], ['流行词', 6, 'dep', 'NN'], ['，', 6, 'punct', 'PU'], ['是', 0, 'root', 'VC'], ['韩语', 9, 'nn', 'NN'], ['“', 9, 'punct', 'PU'], ['우리', 12, 'assmod', 'NN'], ['”', 9, 'punct', 'PU'], ['的', 9, 'assm', 'DEG'], ['音译', 6, 'attr', 'NN'], ['，', 6, 'punct', 'PU'], ['意思', 15, 'top', 'NN'], ['是', 6, 'conj', 'VC'], ['“', 17, 'punct', 'PU'], ['我们', 21, 'conj', 'PN'], ['”', 17, 'punct', 'PU'], ['、', 21, 'punct', 'PU'], ['“', 21, 'punct', 'PU'], ['我们', 15, 'attr', 'PN'], ['的', 21, 'assm', 'DEG'], ['”', 21, 'punct', 'PU'], ['。', 6, 'punct', 'PU'], ['可以', 37, 'mmod', 'VV'], ['把', 37, 'ba', 'BA'], ['很', 28, 'advmod', 'AD'], ['亲密', 36, 'rcmod', 'VA'], ['的', 28, 'cpm', 'DEC'], ['同辈', 36, 'conj', 'NN'], ['、', 36, 'punct', 'PU'], ['恋人', 36, 'conj', 'NN'], ['、', 36, 'punct', 'PU'], ['喜欢', 36, 'rcmod', 'VV'], ['的', 34, 'cpm', 'DEC'], ['明星', 37, 'nsubj', 'NN'], ['称为', 6, 'conj', 'VV'], ['：', 37, 'punct', 'PU'], ['WuLi + ', 40, 'nn', 'NR'], ['名字', 37, 'dobj', 'NN'], ['。', 6, 'punct', 'PU'], ['或者是', 49, 'cc', 'CC'], ['和', 45, 'prep', 'P'], ['自己', 43, 'pobj', 'PN'], ['有', 49, 'rcmod', 'VE'], ['亲属', 47, 'nn', 'NN'], ['关系', 45, 'dobj', 'NN'], ['的', 45, 'cpm', 'DEC'], ['人', 37, 'nsubj', 'NN'], ['，', 37, 'punct', 'PU'], ['可以', 56, 'mmod', 'VV'], ['用', 58, 'prep', 'P'], ['우리', 55, 'nn', 'NN'], ['+', 55, 'punct', 'PU'], ['称谓', 52, 'pobj', 'NN'], ['是', 37, 'dep', 'VC'], ['朝鲜语', 55, 'nn', 'NN'], ['交谈', 65, 'rcmod', 'VV'], ['的', 58, 'cpm', 'DEC'], ['一', 61, 'nummod', 'CD'], ['种', 65, 'clf', 'M'], ['常用', 65, 'assmod', 'JJ'], ['的', 62, 'assm', 'DEG'], ['表达', 65, 'nn', 'NN'], ['方式', 56, 'attr', 'NN'], ['。', 6, 'punct', 'PU']], [['台风', 8, 'nsubj', 'NN'], ['（', 5, 'punct', 'PU'], ['英语', 5, 'nsubj', 'NN'], ['：', 5, 'punct', 'PU'], ['Typhoon', 8, 'nsubj', 'NR'], ['）', 5, 'punct', 'PU'], ['，', 8, 'punct', 'PU'], ['属于', 0, 'root', 'VV'], ['热带', 10, 'nn', 'NN'], ['气旋', 13, 'assmod', 'NN'], ['的', 10, 'assm', 'DEG'], ['一', 13, 'nummod', 'CD'], ['种', 8, 'range', 'M'], ['。', 8, 'punct', 'PU'], ['热带', 16, 'nn', 'NN'], ['气旋', 17, 'nsubj', 'NN'], ['是', 8, 'conj', 'VC'], ['发生', 27, 'rcmod', 'VV'], ['在', 18, 'prep', 'P'], ['热带', 22, 'conj', 'NN'], ['或', 22, 'cc', 'CC'], ['副热带', 23, 'nn', 'NN'], ['洋面', 24, 'lobj', 'NN'], ['上', 19, 'plmod', 'LC'], ['的', 18, 'cpm', 'DEC'], ['低压', 27, 'nn', 'NN'], ['涡旋', 17, 'attr', 'NN'], ['，', 17, 'punct', 'PU'], ['是', 8, 'conj', 'VC'], ['一', 31, 'nummod', 'CD'], ['种', 39, 'clf', 'M'], ['强大', 39, 'rcmod', 'VA'], ['而', 32, 'cc', 'CC'], ['深厚', 32, 'dep', 'VA'], ['的', 32, 'cpm', 'DEC'], ['“', 39, 'punct', 'PU'], ['热带', 39, 'nn', 'NN'], ['天气', 39, 'nn', 'NN'], ['系统', 29, 'attr', 'NN'], ['”', 39, 'punct', 'PU'], ['。', 8, 'punct', 'PU'], ['我', 43, 'nn', 'PN'], ['国', 65, 'nsubj', 'NN'], ['把', 65, 'ba', 'BA'], ['南海', 48, 'conj', 'NR'], ['与', 48, 'cc', 'CC'], ['西北', 48, 'nn', 'NN'], ['太平洋', 51, 'assmod', 'NR'], ['的', 48, 'assm', 'DEG'], ['热带', 51, 'nn', 'NN'], ['气旋', 65, 'nsubj', 'NN'], ['按', 65, 'prep', 'P'], ['其', 55, 'nn', 'PN'], ['底层', 56, 'nn', 'NN'], ['中心', 56, 'nn', 'NN'], ['附近', 60, 'nn', 'NN'], ['最', 58, 'advmod', 'AD'], ['大', 60, 'amod', 'JJ'], ['平均', 60, 'amod', 'JJ'], ['风力', 64, 'conj', 'NN'], ['（', 62, 'punct', 'PU'], ['风速', 64, 'nn', 'NN'], ['）', 62, 'punct', 'PU'], ['大小', 52, 'pobj', 'NN'], ['划分', 8, 'conj', 'VV'], ['为', 65, 'dep', 'VC'], ['6', 68, 'nummod', 'CD'], ['个', 69, 'clf', 'M'], ['等级', 65, 'dobj', 'NN'], ['，', 8, 'punct', 'PU'], ['其中', 73, 'nsubj', 'NN'], ['风力', 73, 'nsubj', 'NN'], ['达', 80, 'nsubj', 'VV'], ['12', 75, 'nummod', 'CD'], ['级', 77, 'lobj', 'M'], ['或', 75, 'cc', 'CC'], ['以上', 73, 'loc', 'LC'], ['的', 73, 'cpm', 'DEC'], ['，', 65, 'punct', 'PU'], ['统称', 8, 'conj', 'VV'], ['为', 80, 'dep', 'VC'], ['台风', 80, 'dobj', 'NN'], ['。', 8, 'punct', 'PU']]]
```

我在网上查了，发现不全，还有就是这四个属性 `'级', 77, 'lobj', 'M'` 分别代表什么意思呢？期待您的解答。

**Comment by fdugzc** [comment]
您好，fastHan在POS和依存分析上使用的是CTB 9语料库，对于找不到的标签您可以在该项目的网站[https://www.cs.brandeis.edu/~clp/ctb/](url)提供的guidelines中找到更详细的说明。
对于`'级', 77, 'lobj', 'M'`，其中 级 是当前token；77 和 lobj 是依存分析的信息，代表指向当前token的依存弧源点为第77个token，该依存弧的标签为lobj；M 是词性标注的标签。

**Comment by fdugzc** [comment]
您好，fastHan在POS和依存分析上使用的是CTB 9语料库，对于找不到的标签您可以在该项目的网站https://www.cs.brandeis.edu/~clp/ctb/提供的guidelines中找到更详细的说明。
对于['级', 77, 'lobj', 'M']，其中 级 是当前token；77 和 lobj 是依存分析的信息，代表指向当前token的依存弧源点为第77个token，该依存弧的标签为lobj；M 是词性标注的标签。

**Comment by fdugzc** [comment]
您好，fastHan在POS和依存分析上使用的是CTB 9语料库，对于找不到的标签您可以在该项目的网站  https://www.cs.brandeis.edu/~clp/ctb/  提供的guidelines中找到更详细的说明。
对于'级', 77, 'lobj', 'M'，其中 级 是当前token；77 和 lobj 是依存分析的信息，代表指向当前token的依存弧源点为第77个token，该依存弧的标签为lobj；M 是词性标注的标签。

**Comment by HarborZeng** [comment]
> 您好，fastHan在POS和依存分析上使用的是CTB 9语料库，对于找不到的标签您可以在该项目的网站 https://www.cs.brandeis.edu/~clp/ctb/ 提供的guidelines中找到更详细的说明。
> 对于'级', 77, 'lobj', 'M'，其中 级 是当前token；77 和 lobj 是依存分析的信息，代表指向当前token的依存弧源点为第77个token，该依存弧的标签为lobj；M 是词性标注的标签。

感谢指引，我去学习下。

**Comment by hl0737** [comment]
> 您好，fastHan在POS和依存分析上使用的是CTB 9语料库，对于找不到的标签您可以在该项目的网站 https://www.cs.brandeis.edu/~clp/ctb/ 提供的guidelines中找到更详细的说明。 对于'级', 77, 'lobj', 'M'，其中 级 是当前token；77 和 lobj 是依存分析的信息，代表指向当前token的依存弧源点为第77个token，该依存弧的标签为lobj；M 是词性标注的标签。

作者您好, 我看使用的CTB9, 然后提供的网站上Guideline for Bracketing (final version): [ps-file], [pdf-file] 这里面的pdf版本是ctb3.0, 我目前不太清楚CTB9的dependency parsing有哪些标签, 请问这个标签体系该到哪里查找到呢? 感谢作者~~

**Comment by fdugzc** [comment]
> > 您好，fastHan在POS和依存分析上使用的是CTB 9语料库，对于找不到的标签您可以在该项目的网站 https://www.cs.brandeis.edu/~clp/ctb/ 提供的guidelines中找到更详细的说明。 对于'级', 77, 'lobj', 'M'，其中 级 是当前token；77 和 lobj 是依存分析的信息，代表指向当前token的依存弧源点为第77个token，该依存弧的标签为lobj；M 是词性标注的标签。
> 
> 作者您好, 我看使用的CTB9, 然后提供的网站上Guideline for Bracketing (final version): [ps-file], [pdf-file] 这里面的pdf版本是ctb3.0, 我目前不太清楚CTB9的dependency parsing有哪些标签, 请问这个标签体系该到哪里查找到呢? 感谢作者~~

我看到一篇博客上讲的还挺全的，可以参考下    https://blog.csdn.net/lihaitao000/article/details/51812618

**Comment by hl0737** [comment]
> > > 您好，fastHan在POS和依存分析上使用的是CTB 9语料库，对于找不到的标签您可以在该项目的网站 https://www.cs.brandeis.edu/~clp/ctb/ 提供的guidelines中找到更详细的说明。 对于'级', 77, 'lobj', 'M'，其中 级 是当前token；77 和 lobj 是依存分析的信息，代表指向当前token的依存弧源点为第77个token，该依存弧的标签为lobj；M 是词性标注的标签。
> > 
> > 
> > 作者您好, 我看使用的CTB9, 然后提供的网站上Guideline for Bracketing (final version): [ps-file], [pdf-file] 这里面的pdf版本是ctb3.0, 我目前不太清楚CTB9的dependency parsing有哪些标签, 请问这个标签体系该到哪里查找到呢? 感谢作者~~
> 
> 我看到一篇博客上讲的还挺全的，可以参考下 https://blog.csdn.net/lihaitao000/article/details/51812618

我找到一个, 特别好, https://hanlp.hankcs.com/docs/annotations/dep/sd_zh.html

这个hanLP跟我们的fastHan有关系吗? 都有Han三个char

**Comment by fdugzc** [comment]
> > > > 您好，fastHan在POS和依存分析上使用的是CTB 9语料库，对于找不到的标签您可以在该项目的网站 https://www.cs.brandeis.edu/~clp/ctb/ 提供的guidelines中找到更详细的说明。 对于'级', 77, 'lobj', 'M'，其中 级 是当前token；77 和 lobj 是依存分析的信息，代表指向当前token的依存弧源点为第77个token，该依存弧的标签为lobj；M 是词性标注的标签。
> > > 
> > > 
> > > 作者您好, 我看使用的CTB9, 然后提供的网站上Guideline for Bracketing (final version): [ps-file], [pdf-file] 这里面的pdf版本是ctb3.0, 我目前不太清楚CTB9的dependency parsing有哪些标签, 请问这个标签体系该到哪里查找到呢? 感谢作者~~
> > 
> > 
> > 我看到一篇博客上讲的还挺全的，可以参考下 https://blog.csdn.net/lihaitao000/article/details/51812618
> 
> 我找到一个, 特别好, https://hanlp.hankcs.com/docs/annotations/dep/sd_zh.html
> 
> 这个hanLP跟我们的fastHan有关系吗? 都有Han三个char

这个确实挺全的；我们和hanlp没有什么关系，巧合吧：）
