### ISSUE TITLE
吐槽一下分词的准确性

### ISSUE THREAD

**Issue by HarborZeng** [fastnlp/fastHan#7]
fastHan:

['谢谢', '邀', '请', '前', '面有', '人说不', '知', '道', '马', '飞', '飞是', '谁，', '特地', '百', '度', '一下。', '马飞飞', '原', '名彭逸', '飞', '庆', '经也', '是一', '职', '业', '选', '手', '但并', '没', '能有', '什', '大造化', '在俱', '乐部', '合', '约', '限', '制', '下，', '只能', '终', '日', '雪藏', '就在此', '时被', '卢', '本伟', '发掘', '直播', '天赋', '开', '始', '尝试', '带', '他进', '行', '双人直', '播。', '马', '飞飞', '原', '先的', 'I', 'D', '飞飞', '在直', '播', '中被', '观', '众带', '节', '奏', '指出', '他爱', '拍', '老板', '马', '屁，', '被观', '众老', '爷', '称', '作马', '屁', '飞', '节', '奏', '带', '多了', '干', '脆认', '名字，', '改', '马飞', '飞了', '作者：', 'B', 'en', 'n', 'u\n链接：', 'h', 'ttps://www.zhihu.com/question/264483756/answer/28431', '10', '5\n来', '源：知', '著', '作权', '作者', '商业', '转载', '请联', '系作', '获', '得授', '权，', '非', '商业', '转载', '请']

jieba:

['谢谢', '邀请', '有人', '说', '马飞飞', '特地', '百度', '…', '…', '马飞飞', '原名', '彭逸飞', '重庆', '职业', '选手', '没能', '造化', '俱乐部', '合约', '只能', '终日', '雪藏', '卢本伟', '发掘', '直播', '天赋', '尝试', '带', '双人', '直播', '马飞飞', '原先', 'ID', '飞飞', '直播', '中', '观众', '带', '节奏', '指出', '爱', '拍', '老板', '马屁', '观众', '老爷', '称作', '马屁', '飞', '节奏', '带', '干脆', '认下', '名字', '改叫', '马飞飞', '作者', 'Bennu', '链接', 'https', 'www', 'zhihu', 'question', '264483756', 'answer', '284311005', '来源', '知乎', '著作权', '作者', '商业', '转载', '请', '作者', '授权', '非商业', '转载', '请', '注明', '出处']

当然，我在切割后过滤了停用词，但是这个效果对比未免有点太夸张了，是样本的错吗？

**Comment by fdugzc** [comment]
可以发现您输出的分词结果发生了index的偏移，可能是由于您输入的句子的首尾包含空格，触发了<=1.2版本fastHan的bug。现在fastHan已更新至1.3，您可以重新实验下效果。对bug带给您的困扰深表歉意

**Comment by fdugzc** [comment]
或者您在输入模型前先将句子首尾的空格去掉，试验下效果

**Comment by HarborZeng** [comment]
> 可以发现您输出的分词结果发生了index的偏移，可能是由于您输入的句子的首尾包含空格，触发了<=1.2版本fastHan的bug。现在fastHan已更新至1.3，您可以重新实验下效果。对bug带给您的困扰深表歉意

感谢作者大大，修复之后就正常了呢，分词十分准确，我会继续使用，帮你发现更多隐藏的问题，让这个工具变得更好~
