### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by Vincent131499** [fastnlp/fastHan#8]
感谢你杰出的工作，请问对于具体的模型的训练能否具体说明呢？比如数据的格式，模型的加载等

**Comment by fdugzc** [comment]
在论文完成后不管能不能发表，届时都会贴上来，里面会详细得说明模型结构和训练策略。
对于数据格式，train.py加载的是处理好并用torch.save保存的数据，是fastNLP里的DataSet类，其中包含了输入串、序列长度、标签序列等等。
对于加载模型，在训练和测试时是直接用torch. save，torch. load加载整个模型；在FastHan()初始化时则是先随机初始化一个模型，再torch. load模型的state dict并赋值

**Comment by chyun** [comment]
大神, 模型训练策略能详细说一下吗?
