### ISSUE TITLE
语句太长报错~

### ISSUE THREAD

**Issue by ScottishFold007** [fastnlp/fastHan#9]
求教，语句太长（512个字以外）报错，怎么解决呢？

**Comment by fdugzc** [comment]
因为预训练的BERT对字符串最大长度做出限制，所以除非再自己训一个BERT，这个问题目前无法解决。对于用户来说，输入的字符串长度需要小于等于509 。实在过长的字符串，可以自己先通过“。？！……”等符号先分割一下再输入。

**Comment by ScottishFold007** [comment]
> 因为预训练的BERT对字符串最大长度做出限制，所以除非再自己训一个BERT，这个问题目前无法解决。对于用户来说，输入的字符串长度需要小于等于509 。实在过长的字符串，可以自己先通过“。？！……”等符号先分割一下再输入。

有个Longformer（ The Long-Document Transformer），不知道能不能缓解这个问题

**Comment by fdugzc** [comment]
我再研究一下，下次更新的时候会考虑这个问题的

**Comment by xpqiu** [comment]
> 我再研究一下，下次更新的时候会考虑这个问题的

这个可以工程方式解决。先分句，每句分词后再合并输出。

**Comment by ScottishFold007** [comment]
我担心篇章级文本的语境变了，分词会出问题



---原始邮件---
发件人: "Xipeng Qiu"<notifications@github.com&gt;
发送时间: 2020年6月20日(周六) 凌晨0:27
收件人: "fastnlp/fastHan"<fastHan@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Scottish_Fold007"<gaochangkuan01@foxmail.com&gt;;
主题: Re: [fastnlp/fastHan] 语句太长报错~ (#9)




  
我再研究一下，下次更新的时候会考虑这个问题的
  
这个可以工程方式解决。先分句，每句分词后再合并输出。
